# EXPERIMENT 2 - NUMERICAL PYTHON (NUMPY)

Vallarit, Marick Andrei T.
2ECE-C

### NORMALIZATION PROBLEM:

In [2]:
import numpy as np # Import numpy library

X = np.random.rand(5, 5) # Construct a 5 x 5 array with random integers

# Normalize the array
Xmean = X.mean() 
Xstd = X.std()
Xnormalized = (X - Xmean) / Xstd

np.save('X_normalized.npy', Xnormalized) # Save the result of the normalized array as a file named X_normalized.npy

print(Xnormalized) # Print result just to check

[[-1.43284997  0.77120825  0.25710994 -0.01093235  1.14505757]
 [-0.1806092   1.00287039 -0.97448315  1.36846219 -1.47045064]
 [-0.26523892 -0.42063726 -0.86103245 -1.41693486  0.75828337]
 [ 1.38409513 -0.35546331 -0.78274944 -0.59681767 -1.09398446]
 [ 1.37039907  1.37472261  1.27342328  0.42314457 -1.26659269]]


### DIVISIBLE BY 3 PROBLEM:

In [4]:
import numpy as np # Import numpy library

A = np.arange(1,101) # Get the first positive integers from 1 - 100
Aarray = A.reshape(10,10) ** 2 # Construct a 10x10 array, then get the squares of each integers

divisible = Aarray[Aarray % 3 == 0] # Get the numbers that are divisible by 3

np.save('div_by_3.npy', divisible) # Save the result as a file named div_by_3.npy

print(divisible) # Print the elements that are divisible by 3 just to check

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
